name: CD Development

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Trigger Render Deploy
      run: curl ${{ secrets.RENDER_DEV_HOOK }}
